# Generated by Django 4.2.7 on 2023-11-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='khanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('khanda', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='american',
        ),
    ]
