# Generated by Django 4.2.7 on 2023-11-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database1', '0002_khanda_delete_american'),
    ]

    operations = [
        migrations.CreateModel(
            name='regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regions', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='khanda',
            name='khanda',
            field=models.CharField(max_length=20),
        ),
    ]
