# Generated by Django 4.2.7 on 2023-11-16 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database1', '0005_regions_khanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='regions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database1.regions'),
        ),
    ]
