# Generated by Django 4.2.7 on 2023-11-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database1', '0006_countries_regions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countries',
            old_name='countries',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='khanda',
            old_name='khanda',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='regions',
            old_name='khanda',
            new_name='name',
        ),
    ]
