# Generated by Django 4.2.7 on 2023-11-16 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database1', '0009_belize'),
    ]

    operations = [
        migrations.DeleteModel(
            name='belize',
        ),
    ]
