# Generated by Django 4.2.7 on 2023-11-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database1', '0010_delete_belize'),
    ]

    operations = [
        migrations.CreateModel(
            name='belize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='belize/')),
                ('heading', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('image2', models.ImageField(upload_to='belize/')),
                ('heading2', models.CharField(max_length=40)),
                ('description2', models.TextField()),
            ],
        ),
    ]
