# Generated by Django 4.2.7 on 2023-11-22 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database1', '0012_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='field_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='belize/')),
                ('heading', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('image2', models.ImageField(upload_to='belize/')),
                ('heading2', models.CharField(max_length=40)),
                ('description2', models.TextField()),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database1.country')),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database1.field_type')),
                ('khanda', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database1.khanda')),
            ],
        ),
    ]
