# Generated by Django 4.2.7 on 2023-11-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database1', '0013_field_type_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='heading',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='blog',
            name='heading2',
            field=models.CharField(max_length=80),
        ),
    ]
