# Generated by Django 4.2.7 on 2023-11-29 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database1', '0015_rename_image_blog_image11_rename_image2_blog_image22'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='field_type',
            new_name='fieldtype',
        ),
    ]
