# Generated by Django 4.2.7 on 2023-12-01 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database1', '0019_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='favourite_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database1.favourite'),
        ),
    ]
